// JsFromRoutes CacheKey ec76c1f9cbad39e4a8b8cccbfbc7eb68
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/alerts'),
  workspace: /* #__PURE__ */ definePathHelper('get', '/w/:workspace_id/alerts'),
}
