// JsFromRoutes CacheKey 1803ad796db182578cd02d985144781a
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  login: /* #__PURE__ */ definePathHelper('get', '/login'),
  logout: /* #__PURE__ */ definePathHelper('get', '/logout'),
}
