// JsFromRoutes CacheKey 6a2e5bd9e388e8e142e37483a7752702
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/automations'),
  workspace: /* #__PURE__ */ definePathHelper('get', '/w/:workspace_id/automations'),
}
