// JsFromRoutes CacheKey a529f2d02baad691fab7d7979c375370
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/competitors'),
  workspace: /* #__PURE__ */ definePathHelper('get', '/w/:workspace_id/competitors'),
}
