// JsFromRoutes CacheKey 93cec4c1c8439569124ddc225e80996e
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/connections'),
  workspace: /* #__PURE__ */ definePathHelper('get', '/w/:workspace_id/connections'),
}
