// JsFromRoutes CacheKey 76a9ce411550c725dbbc6b2785e5e2e8
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/w/:workspace_id'),
}
