// JsFromRoutes CacheKey 43b22d45400fc305e5cfbfc07f4ee605
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/inbox'),
  workspace: /* #__PURE__ */ definePathHelper('get', '/w/:workspace_id/inbox'),
}
