// JsFromRoutes CacheKey 360d77a629a6fdffecf3112b5826106b
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/insights'),
  workspace: /* #__PURE__ */ definePathHelper('get', '/w/:workspace_id/insights'),
}
