// JsFromRoutes CacheKey 7ebd74b8365c5b5ce6cfcfde77a13340
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/w/:workspace_id/integrations'),
  connect: /* #__PURE__ */ definePathHelper('post', '/w/:workspace_id/integrations/:provider_key/connect'),
  providerApp: /* #__PURE__ */ definePathHelper('post', '/w/:workspace_id/integrations/:provider_key/provider_app'),
  credentials: /* #__PURE__ */ definePathHelper('post', '/w/:workspace_id/integrations/:provider_key/credentials'),
  disconnect: /* #__PURE__ */ definePathHelper('delete', '/w/:workspace_id/integrations/connections/:id'),
  sync: /* #__PURE__ */ definePathHelper('post', '/w/:workspace_id/integrations/connections/:id/sync'),
}
