// JsFromRoutes CacheKey 20e5df9d5de5d42ffce4ef85dc3618e7
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/reports'),
  workspace: /* #__PURE__ */ definePathHelper('get', '/w/:workspace_id/reports'),
}
