// JsFromRoutes CacheKey ed4d9ffee9f0494ef33cef530805016a
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/settings'),
  workspace: /* #__PURE__ */ definePathHelper('get', '/w/:workspace_id/settings'),
}
