// JsFromRoutes CacheKey 5bc2fc239651d2a26be1e0c587bb7cb9
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  show: /* #__PURE__ */ definePathHelper('get', '/setup/:step'),
  update: /* #__PURE__ */ definePathHelper('patch', '/setup'),
}
