// JsFromRoutes CacheKey 05027f9af3aacd510d48b1c07544f802
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/team'),
  workspace: /* #__PURE__ */ definePathHelper('get', '/w/:workspace_id/team'),
}
