// JsFromRoutes CacheKey 040d004692e18e7bfaedb0f6647e8f1e
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/themes'),
  workspace: /* #__PURE__ */ definePathHelper('get', '/w/:workspace_id/themes'),
}
