// JsFromRoutes CacheKey c5cd5a26d730f8a9c1f52dc2c10ed5c8
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  switch: /* #__PURE__ */ definePathHelper('post', '/w/:workspace_id/switch'),
}
