// JsFromRoutes CacheKey fdd65854e39488ce5e296a04fbfe0df0
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  inbox: /* #__PURE__ */ definePathHelper('get', '/w/:workspace_id/inbox/:view_id'),
  contacts: /* #__PURE__ */ definePathHelper('get', '/w/:workspace_id/contacts'),
  rules: /* #__PURE__ */ definePathHelper('get', '/w/:workspace_id/rules'),
  settings: /* #__PURE__ */ definePathHelper('get', '/w/:workspace_id/settings'),
}
