// JsFromRoutes CacheKey 10fdfbf1caebf7997fd88c51ae58ff80
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  show: /* #__PURE__ */ definePathHelper('get', '/w/:workspace_id/api/conversations/:conversation_id/ai'),
  analyze: /* #__PURE__ */ definePathHelper('post', '/w/:workspace_id/api/conversations/:conversation_id/ai/analyze'),
}
