// JsFromRoutes CacheKey 65d9076a22177e15f64d98b5ab6e363c
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('post', '/w/:workspace_id/api/conversations/:conversation_id/rag/index'),
  query: /* #__PURE__ */ definePathHelper('post', '/w/:workspace_id/api/conversations/:conversation_id/rag/query'),
}
