// JsFromRoutes CacheKey 9261ef55b3b77365636eae5537f57612
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/w/:workspace_id/api/conversations'),
  update: /* #__PURE__ */ definePathHelper('patch', '/w/:workspace_id/api/conversations/:id'),
  messages: /* #__PURE__ */ definePathHelper('get', '/w/:workspace_id/api/conversations/:id/messages'),
  reply: /* #__PURE__ */ definePathHelper('post', '/w/:workspace_id/api/conversations/:id/reply'),
}
