// JsFromRoutes CacheKey 087567cb458f2453456e48db99740178
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  update: /* #__PURE__ */ definePathHelper('patch', '/w/:workspace_id/api/messages/:id'),
}
