// JsFromRoutes CacheKey 1a58cbcd390a5f6061eddb3f2c6178b5
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  query: /* #__PURE__ */ definePathHelper('post', '/w/:workspace_id/api/rag/query'),
}
