// JsFromRoutes CacheKey cc7015a26ae5f0269b0081615bffbc36
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  callback: /* #__PURE__ */ definePathHelper('get', '/integrations/oauth/:provider_key/callback'),
}
